on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Send Deploy Request
      id: deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://alitayyeb.ir/deploy-from-git'
        method: 'GET'
        timeout: 20000
        customHeaders: '{"Authorization": "${{ secrets.DEPLOY_KEY }}"}'
    - name: Log Deploy Response
      run: |
        echo "detail: ${{ fromJson(steps.deploy.outputs.response).detail }}"
        echo "stdout: ${{ fromJson(steps.deploy.outputs.response).stdout }}"
        echo "stderr: ${{ fromJson(steps.deploy.outputs.response).stderr }}"
    - name: Check deploy failure
      if: ${{ failure() || !fromJSON(steps.deploy.outputs.response).success}}
      run: exit 1
